### ISSUE TITLE
char/none size calculation irritating

### ISSUE THREAD

**Issue by frehberg** [hrektts/cdr-rs#3]
Two issues in  size.rs I see the following code.

First:

```rust
   fn serialize_char(self, v: char) -> Result<Self::Ok> {
        self.add_size(v.len_utf8() as u64)
    }
```

A char in CDR is always u8, it is irritating, that code code here is assuming a dynamic size depending on utf encoding

AFAICS, it should be:

```rust
 fn serialize_char(self, v: char) -> Result<Self::Ok> {
        // no alignment required increment byte-size 1
        self.add_size(1 as u8)
 }
```

Second: 

Another weird thing is this code, it will add byte-size of u8 to the counte (1)r, but according to name it should add 0!?
```
    fn serialize_none(self) -> Result<Self::Ok> {
        self.add_value(0 as u8)
    }
```

**Comment by hrektts** [comment]
First:

Agree. The specification says that:

> a single instance of the char type may hold only one octet of any multibyte character encoding

Would you like to PR it?

Second:

I decided that the (de)serialization function provided by the lib does not work with `Option` type because the serialized type requires a flag indicating whether the value is `Some` or `None`. Unfortunately, such kind of flags are not documented in the specification. 

Regarding the way you commented, if the size of the serialized data is 0, IMHO, the data cannot be deserialize.

**Comment by frehberg** [comment]
I will send a PR for the first item.
As for the second issue, the union-type might be a good match. 
I am implementing an OMG-IDL-2-Rust code-generator, please take a look at the language mapping for type "union" https://github.com/frehberg/rtps-gen
This code-generator would also work for CORBA-data-structures, interfaces are not generated so far.
I intend to use your CDR-crate as serde-dapter ;)

**Comment by frehberg** [comment]
please see the patch #5

**Comment by hrektts** [comment]
Thank you for using the library :). Originally I also write this library to handle RTPS data.

For your library, the union-type might work well to (de)serialize `None`. On the other hand, I think that it  get the following code be un-deserializable:

```rust
struct {
    a: Option<i32>,
    b: Option<i32>,
    c: Option<i32>,
}
```
